// src/components/ChronicleView.jsx
import React from 'react';

const ChronicleView = ({ chronicleData, isLoading }) => {
  if (isLoading) {
    return (
      <div className="bg-gray-900 text-cyan-300 p-6 rounded-lg animate-pulse">
        <h2 className="text-xl font-mono">Converging truth nodes...</h2>
        <p>Listening to metadata whispers.</p>
      </div>
    );
  }

  if (!chronicleData) {
    return (
      <div className="bg-gray-900 text-gray-500 p-6 rounded-lg">
        <p>Adjust inputs to generate your first Chronicle.</p>
      </div>
    );
  }

  const { 
    title, 
    subtitle, 
    narrative, 
    fidelity_score, 
    checksum,
    convergence_points 
  } = chronicleData;

  return (
    <div className="bg-gradient-to-br from-gray-900 to-indigo-950 border border-cyan-800 rounded-xl p-6 text-white shadow-lg">
      <div className="flex justify-between items-start mb-4">
        <h2 className="text-2xl font-bold text-cyan-300">{title}</h2>
        <span className="bg-cyan-900/30 px-2 py-1 rounded text-sm">
          Fidelity: {fidelity_score}/10
        </span>
      </div>

      <p className="text-cyan-100 italic mb-4">{subtitle}</p>

      <blockquote className="border-l-4 border-cyan-500 pl-4 my-4 text-emerald-100">
        {narrative}
      </blockquote>

      {convergence_points && convergence_points.length > 0 && (
        <div className="mt-4 text-xs text-gray-400">
          <strong>Truth Nodes:</strong> {convergence_points.join(', ')}
        </div>
      )}

      <div className="mt-6 pt-4 border-t border-gray-700 text-xs text-gray-500">
        <div>Checksum: <code className="text-cyan-400">{checksum}</code></div>
        <div className="mt-1">Generated by the One Ten Protocol</div>
      </div>
    </div>
  );
};

export default ChronicleView;
